services:
    p804488s4gs0k0kwc4080wg0-174340743923:
        image: "node:20-alpine"
        container_name: p804488s4gs0k0kwc4080wg0-174340743923
        working_dir: /app
        command: node server.js
        restart: unless-stopped
        expose:
            - "3000"
        networks:
            coolify:
                aliases:
                    - p804488s4gs0k0kwc4080wg0-174340743923
        mem_limit: "0"
        memswap_limit: "0"
        mem_swappiness: 60
        mem_reservation: "0"
        cpus: 0.0
        cpu_shares: 1024
        environment:
            - NODE_ENV=production
            - PORT=3000
            - HOST=0.0.0.0
            - NEXT_PUBLIC_SUPABASE_URL=https://vmvojkmaiuwidrduiotn.supabase.co
            - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdm9qa21haXV3aWRyZHVpb3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzODY4ODksImV4cCI6MjA4Nzk2Mjg4OX0.iXMJCfzWOtPlvCNYZsIjjNZniPbkvoBkzbJYtj9bEyE
            - DATABASE_URL=file:/app/data/fleet.db
            - NEXT_PUBLIC_REQUIRE_EMAIL_VERIFICATION=false
        volumes:
            - /tmp/new-deploy:/app
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.http-0-p804488s4gs0k0kwc4080wg0.entryPoints=http
            - traefik.http.routers.http-0-p804488s4gs0k0kwc4080wg0.middlewares=redirect-to-https
            - "traefik.http.routers.http-0-p804488s4gs0k0kwc4080wg0.rule=Host(`fleet.ashbi.ca`) && PathPrefix(`/`)"
            - traefik.http.routers.http-0-p804488s4gs0k0kwc4080wg0.service=http-0-p804488s4gs0k0kwc4080wg0
            - traefik.http.routers.https-0-p804488s4gs0k0kwc4080wg0.entryPoints=https
            - traefik.http.routers.https-0-p804488s4gs0k0kwc4080wg0.middlewares=gzip
            - "traefik.http.routers.https-0-p804488s4gs0k0kwc4080wg0.rule=Host(`fleet.ashbi.ca`) && PathPrefix(`/`)"
            - traefik.http.routers.https-0-p804488s4gs0k0kwc4080wg0.service=https-0-p804488s4gs0k0kwc4080wg0
            - traefik.http.routers.https-0-p804488s4gs0k0kwc4080wg0.tls.certresolver=letsencrypt
            - traefik.http.routers.https-0-p804488s4gs0k0kwc4080wg0.tls=true
            - traefik.http.services.http-0-p804488s4gs0k0kwc4080wg0.loadbalancer.server.port=3000
            - traefik.http.services.https-0-p804488s4gs0k0kwc4080wg0.loadbalancer.server.port=3000
            - "caddy_0.encode=zstd gzip"
            - "caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}"
            - "caddy_0.handle_path=/*"
            - caddy_0.header=-Server
            - "caddy_0.try_files={path} /index.html /index.php"
            - "caddy_0=https://fleet.ashbi.ca"
            - caddy_ingress_network=coolify
            - coolify.managed=true
            - coolify.version=4.0.0-beta.463
            - coolify.applicationId=22
            - coolify.type=application
            - coolify.name=p804488s4gs0k0kwc4080wg0
            - coolify.resourceName=fleetflow-mvp
            - coolify.projectName=github-projects
            - coolify.serviceName=fleetflow-mvp
            - coolify.environmentName=production
            - coolify.pullRequestId=0
networks:
    coolify:
        external: true
        name: coolify
        attachable: true
