#!/bin/bash

echo "# 🚀 COPY AND PASTE THESE INTO COOLIFY ENVIRONMENT VARIABLES"
echo ""
echo "NEXTAUTH_URL=https://fleet.ashbi.ca"
echo "NEXTAUTH_SECRET=Rh6rLBvT20Ut6HYUjMTuHOdONFN21baBceOwzW+Yk6I="
echo "DATABASE_URL=\"file:./prod.db\""
echo "NODE_ENV=production"
echo "PORT=3000"
echo "NEXT_PUBLIC_APP_NAME=FleetFlow Pro"
echo "NEXT_PUBLIC_APP_VERSION=1.0.0"
echo ""
echo "# 📋 INSTRUCTIONS:"
echo "# 1. Go to Coolify → Applications → fleetflow-pro"
echo "# 2. Click 'Environment Variables'"
echo "# 3. Add each variable above (name and value)"
echo "# 4. Save and wait for redeploy"
echo "# 5. Then run in terminal:"
echo "#    npx prisma db push"
echo "#    npm run seed"
echo ""
echo "# 🔐 LOGIN CREDENTIALS (after seeding):"
echo "# Admin: admin@fleetflow.com / demo123"
echo "# Fleet Manager: manager@josephsdelivery.com / demo123"
echo "# Driver: driver.mrodriguez@josephsdelivery.com / demo123"