import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { DashboardLayout } from '@/components/layouts/DashboardLayout'
import { useSession } from '@/lib/session'

type Health = { status: 'enabled' | 'disabled' | 'killed' | 'misconfigured'; provider: string; modelVersion: string; configVersion: number; retentionDays?: number; requests: number; averageLatencyMs: number; fallbackRate: number; inputTokens: number; outputTokens: number; cost?: { currency: 'USD'; estimatedUsd: number | null; source: string; asOf: string }; errors: Array<{ code: string; count: number }>; evaluation: null | { version: string;mode:string; passed: boolean; runAt: string;capturedAt:string;stale:boolean;applicable:boolean } }

export default function AiHealthPage() {
  const { data: session, status } = useSession(); const router = useRouter(); const [health, setHealth] = useState<Health | null>(null); const [failed, setFailed] = useState(false); const [saving, setSaving] = useState(false)
  useEffect(() => { if (status === 'unauthenticated') void router.push('/auth/login?callbackUrl=/admin/ai-health'); else if (status === 'authenticated' && session?.user?.role !== 'admin') void router.push('/unauthorized') }, [status, session, router])
  useEffect(() => { if (status !== 'authenticated' || session?.user?.role !== 'admin') return; const controller = new AbortController(); fetch('/api/admin/ai-health', { signal: controller.signal, credentials: 'same-origin' }).then(response => { if (!response.ok) throw new Error('failed'); return response.json() }).then(setHealth).catch(error => { if (error instanceof Error && error.name !== 'AbortError') setFailed(true) }); return () => controller.abort() }, [status, session])
  if (status === 'loading' || (!health && !failed)) return <div role="status" className="p-8 text-slate-600">Loading AI health...</div>
  if (failed) return <div role="alert" className="p-8 text-red-700">AI health could not be loaded.</div>
  if (!health) return null
  const cards = [['Requests (24h)', health.requests], ['Average latency', `${health.averageLatencyMs} ms`], ['Fallback rate', `${Math.round(health.fallbackRate * 100)}%`], ['Token usage', `${health.inputTokens + health.outputTokens}`], ['Estimated cost (24h)', health.cost?.estimatedUsd == null ? 'Unavailable' : `${health.cost.currency} $${health.cost.estimatedUsd.toFixed(6)}`]]
  const saveControls = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true); try { const response = await fetch('/api/admin/ai-settings', { method: 'PUT', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ enabled: data.get('enabled') === 'on', killSwitch: data.get('killSwitch') === 'on', retentionDays: Number(data.get('retentionDays')), expectedConfigVersion: health.configVersion }) }); if (!response.ok) throw new Error('failed'); const settings = await response.json(); setHealth(current => current && ({ ...current, status: settings.killSwitch ? 'killed' : settings.enabled ? 'enabled' : 'disabled', retentionDays: settings.retentionDays, configVersion: settings.configVersion })) } catch { setFailed(true) } finally { setSaving(false) } }
  return <DashboardLayout breadcrumbs={[{ label: 'Dashboard', href: '/dashboard' }, { label: 'Admin' }, { label: 'AI health' }]}>
    <section className="mx-auto max-w-6xl space-y-6" aria-labelledby="ai-health-title">
      <div><h1 id="ai-health-title" className="text-2xl font-bold text-slate-900">AI health</h1><p className="text-sm text-slate-600">Operational metadata only. Prompts and personal data are never shown.</p></div>
      <div className="rounded-lg border bg-white p-4"><span className={`inline-flex rounded-full px-3 py-1 text-sm font-semibold ${health.status === 'enabled' ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-900'}`}>{health.status[0].toUpperCase() + health.status.slice(1)}</span><p className="mt-2 break-words text-sm text-slate-700">{health.provider} / {health.modelVersion} / config v{health.configVersion}</p></div>
      <form onSubmit={saveControls} className="space-y-4 rounded-lg border bg-white p-4" aria-labelledby="ai-controls-title"><h2 id="ai-controls-title" className="font-semibold text-slate-900">Workspace AI controls</h2><label className="flex min-h-11 items-center gap-3"><input name="enabled" type="checkbox" defaultChecked={health.status === 'enabled'} className="h-5 w-5"/> Enable AI for this workspace</label><label className="flex min-h-11 items-center gap-3"><input name="killSwitch" type="checkbox" defaultChecked={health.status === 'killed'} className="h-5 w-5"/> Emergency workspace kill switch</label><label className="block text-sm font-medium text-slate-800">Telemetry retention days<select name="retentionDays" defaultValue={health.retentionDays ?? 30} className="mt-1 block min-h-11 w-full rounded border px-3 sm:max-w-xs"><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select></label><button disabled={saving} className="min-h-11 rounded bg-blue-700 px-4 py-2 font-medium text-white disabled:opacity-60">{saving ? 'Saving...' : 'Save AI controls'}</button></form>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([label, value]) => <div key={label} className="rounded-lg border bg-white p-4"><p className="text-sm text-slate-600">{label}</p><p className="text-2xl font-semibold text-slate-900">{value}</p></div>)}</div>
      <div className="overflow-x-auto rounded-lg border bg-white p-4"><table aria-label="AI errors" className="min-w-full text-left text-sm"><caption className="mb-3 text-left font-semibold text-slate-900">Errors and fallbacks</caption><thead><tr><th scope="col" className="py-2">Code</th><th scope="col" className="py-2">Count</th></tr></thead><tbody>{health.errors.length ? health.errors.map(item => <tr key={item.code}><td className="py-2 font-mono">{item.code}</td><td>{item.count}</td></tr>) : <tr><td colSpan={2} className="py-3 text-slate-600">No errors recorded.</td></tr>}</tbody></table></div>
      <div className="rounded-lg border bg-white p-4"><h2 className="font-semibold text-slate-900">AI evaluation</h2><p className="text-sm text-slate-700">{health.evaluation ? `${health.evaluation.mode === 'deterministic-pipeline' ? 'Deterministic pipeline' : 'Provider quality'} / ${health.evaluation.version} / ${health.evaluation.passed && health.evaluation.applicable && !health.evaluation.stale ? 'Applicable pass' : health.evaluation.stale ? 'Stale' : !health.evaluation.applicable ? 'Not applicable' : 'Failed'} / ${new Date(health.evaluation.capturedAt).toLocaleString()}` : 'No evaluation recorded.'}</p></div>
    </section>
  </DashboardLayout>
}
