import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { DashboardLayout } from '@/components/layouts/DashboardLayout'
import { useSession } from '@/lib/session'

type Config = { configured: boolean; provider?: string; domain?: string; verifiedDomain?: string; fromEmail?: string; updatedAt?: string }

export default function EmailDeliveryPage() {
  const { data: session, status } = useSession(); const router = useRouter(); const [config, setConfig] = useState<Config | null>(null); const [apiKey, setApiKey] = useState(''); const [domain, setDomain] = useState(''); const [verifiedDomain, setVerifiedDomain] = useState(''); const [fromEmail, setFromEmail] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  const admin = String(session?.user?.role ?? '').toLowerCase() === 'admin'
  const load = async () => { const response = await fetch('/api/admin/email/delivery'); if (!response.ok) throw new Error('failed'); const body = await response.json(); setConfig(body.config); setDomain(body.config.domain ?? ''); setVerifiedDomain(body.config.verifiedDomain ?? ''); setFromEmail(body.config.fromEmail ?? '') }
  useEffect(() => { if (status === 'unauthenticated') void router.push('/auth/login?callbackUrl=/admin/email-delivery'); else if (status === 'authenticated' && !admin) void router.push('/unauthorized') }, [status, admin, router])
  useEffect(() => { if (status === 'authenticated' && admin) void load().catch(() => setMessage('Email delivery status could not be loaded.')) }, [status, admin])
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(''); try { const response = await fetch('/api/admin/email/delivery', { method: 'PUT', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ apiKey, domain, verifiedDomain, fromEmail }) }); if (!response.ok) throw new Error('failed'); const body = await response.json(); setConfig(body.config); setApiKey(''); setMessage('Email delivery configuration saved securely.') } catch { setMessage('Configuration could not be saved. Check values and the deployment encryption key.') } finally { setSaving(false) } }
  return <DashboardLayout breadcrumbs={[{ label: 'Dashboard', href: '/dashboard' }, { label: 'Admin' }, { label: 'Email delivery' }]}><main className="mx-auto max-w-2xl space-y-6" aria-labelledby="email-delivery-title"><header><h1 id="email-delivery-title" className="text-2xl font-bold text-slate-900">Transactional email delivery</h1><p className="mt-1 text-sm text-slate-600">Platform administrators only. The Mailgun API key is encrypted at rest and is never displayed after saving.</p></header>{message ? <p role="status" className="rounded border bg-slate-50 p-3 text-sm text-slate-700">{message}</p> : null}<form onSubmit={save} className="space-y-4 rounded border bg-white p-5"><p className="text-sm text-slate-600">Status: {config?.configured ? `Configured${config.updatedAt ? ` on ${new Date(config.updatedAt).toLocaleString()}` : ''}` : 'Not configured'}</p><label className="block text-sm font-medium">Mailgun API key<input required type="password" autoComplete="new-password" value={apiKey} onChange={event => setApiKey(event.target.value)} className="mt-1 block min-h-11 w-full rounded border px-3" /></label><label className="block text-sm font-medium">Sending domain<input required value={domain} onChange={event => setDomain(event.target.value)} placeholder="mg.example.com" className="mt-1 block min-h-11 w-full rounded border px-3" /></label><label className="block text-sm font-medium">Verified Mailgun domain<input required value={verifiedDomain} onChange={event => setVerifiedDomain(event.target.value)} className="mt-1 block min-h-11 w-full rounded border px-3" /></label><label className="block text-sm font-medium">From address<input required value={fromEmail} onChange={event => setFromEmail(event.target.value)} placeholder="Fleetvera <notifications@mg.example.com>" className="mt-1 block min-h-11 w-full rounded border px-3" /></label><button disabled={saving} className="min-h-11 rounded bg-blue-700 px-4 font-medium text-white disabled:opacity-60">{saving ? 'Saving...' : 'Save encrypted configuration'}</button></form></main></DashboardLayout>
}
