import type { Vehicle, Delivery, MaintenanceTask } from '@/services/apiService'

export interface CommandCentreData { vehicles: Vehicle[]; deliveries: Delivery[]; maintenance: MaintenanceTask[] }
export interface CommandCentreProps extends CommandCentreData { partial:boolean; retry:()=>void; decisions:string[]; actions:Array<{label:string;href:string}>; availability:Record<'vehicles'|'deliveries'|'maintenance',boolean>; totals:Record<'vehicles'|'deliveries'|'maintenance',number|null>; onboardingCompleted:boolean }

export function CommandShell({title,partial,retry,availability,children}:{title:string;partial:boolean;retry:()=>void;availability?:CommandCentreProps['availability'];children:React.ReactNode}) { const unavailable=availability?Object.entries(availability).filter(([,ok])=>!ok).map(([name])=>name):[]; return <div className="mx-auto max-w-7xl space-y-6 overflow-x-hidden"><header><h1 className="text-2xl font-bold text-slate-950">{title}</h1><p className="mt-1 text-sm text-slate-600">Decisions and assignments for this workspace</p></header>{partial&&<div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4"><span>Some dashboard data could not be loaded.{unavailable.length?` Unavailable: ${unavailable.join(', ')}.`:''}</span><button className="min-h-[44px] rounded-lg border border-amber-700 px-4 font-medium" onClick={retry} aria-label="Retry loading dashboard">Retry</button></div>}{children}</div> }

export function Exceptions({deliveries,maintenance,availability}:Pick<CommandCentreProps,'deliveries'|'maintenance'|'availability'>) { const blocked=availability.deliveries?deliveries.filter(i=>i.status==='cancelled'):[]; const due=availability.maintenance?maintenance.filter(i=>!i.completed):[]; return <section aria-labelledby="attention-heading" className="rounded-xl border border-amber-200 bg-white p-4 shadow-sm"><h2 id="attention-heading" className="text-lg font-semibold">Needs attention</h2>{!availability.deliveries&&!availability.maintenance?<p className="mt-3 text-sm text-slate-600">Exception sources unavailable.</p>:!blocked.length&&!due.length?<p className="mt-3 text-sm text-slate-600">No current exceptions in available sources.</p>:<ul className="mt-3 space-y-2">{due.slice(0,3).map(i=><li key={String(i.id)} className="rounded-lg bg-amber-50 p-3"><strong>{i.type}</strong><span className="block text-sm">{i.vehicle} - due {i.dueDate}</span></li>)}{blocked.slice(0,3).map(i=><li key={String(i.id)} className="rounded-lg bg-red-50 p-3"><strong>Cancelled delivery</strong><span className="block text-sm">{i.customer} - {i.driver||'Unassigned'}</span></li>)}</ul>}</section> }

export function FleetTotals({totals}:Pick<CommandCentreProps,'totals'>) { return <section aria-labelledby="totals-heading"><h2 id="totals-heading" className="text-lg font-semibold">Fleet totals</h2><dl className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-3">{[['Vehicles',totals.vehicles],['Deliveries',totals.deliveries],['Maintenance',totals.maintenance]].map(([label,value])=><div className="rounded-xl border bg-white p-4" key={label}><dt className="text-sm text-slate-600">{label}</dt><dd className="text-2xl font-bold">{value===null?'Unavailable':value}</dd></div>)}</dl></section> }

function recordFirstUsefulAction() {
  if (typeof window === 'undefined') return
  if (process.env.NODE_ENV === 'test') return
  const keyName = 'fleetvera_pilot_session'
  let sessionKey = window.sessionStorage.getItem(keyName)
  if (!sessionKey) { sessionKey = crypto.randomUUID().replace(/-/g, ''); window.sessionStorage.setItem(keyName, sessionKey) }
  void fetch('/api/pilot/events', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ eventType: 'FIRST_USEFUL_ACTION', sessionKey }) }).catch(() => undefined)
}

export function DecisionActions({decisions,actions}:Pick<CommandCentreProps,'decisions'|'actions'>) { return <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border bg-white p-4"><h2 className="text-lg font-semibold">Top three decisions</h2><ol className="mt-3 list-decimal space-y-2 pl-5">{decisions.map(item=><li key={item}>{item}</li>)}</ol></div>{actions.length>0&&<div className="rounded-xl border bg-white p-4"><h2 className="text-lg font-semibold">Top three actions</h2><div className="mt-3 grid gap-3">{actions.map(item=><a key={item.label} href={item.href} onClick={recordFirstUsefulAction} className="flex min-h-[44px] items-center rounded-lg border px-4 font-medium">{item.label}</a>)}</div></div>}</section> }
