// Real-world fleet management data for food truck delivery service
// Based on typical operations and the WhatsApp image reference

import { Vehicle, Delivery, Client, MaintenanceTask, SOPCategory } from './dataService';

export const realWorldVehicles: Vehicle[] = [
  {
    id: 1,
    name: 'Ford Transit 250',
    status: 'active',
    driver: 'Michael Rodriguez',
    location: '123 Main St - Downtown',
    eta: '15 min',
    mileage: 45230,
    maintenanceDue: false,
    vehicleType: 'cargo_van',
    licensePlate: 'ABC-123',
    year: 2022,
    fuelLevel: 85,
    lastService: '2026-02-15',
    nextService: '2026-03-15'
  },
  {
    id: 2,
    name: 'Mercedes Sprinter 3500',
    status: 'active',
    driver: 'Sarah Johnson',
    location: '456 Oak Ave - Midtown',
    eta: '25 min',
    mileage: 38920,
    maintenanceDue: true,
    vehicleType: 'high_roof_van',
    licensePlate: 'DEF-456',
    year: 2021,
    fuelLevel: 60,
    lastService: '2026-01-20',
    nextService: '2026-02-28'
  },
  {
    id: 3,
    name: 'Ram ProMaster 1500',
    status: 'inactive',
    driver: 'James Wilson',
    location: 'Depot - Service Bay 3',
    eta: 'N/A',
    mileage: 51200,
    maintenanceDue: false,
    vehicleType: 'cargo_van',
    licensePlate: 'GHI-789',
    year: 2020,
    fuelLevel: 45,
    lastService: '2026-02-10',
    nextService: '2026-03-10'
  },
  {
    id: 4,
    name: 'Chevrolet Express 2500',
    status: 'delayed',
    driver: 'Robert Chen',
    location: '789 Pine Rd - Traffic',
    eta: '45 min',
    mileage: 42100,
    maintenanceDue: true,
    vehicleType: 'cargo_van',
    licensePlate: 'JKL-012',
    year: 2023,
    fuelLevel: 70,
    lastService: '2026-01-30',
    nextService: '2026-02-25'
  },
  {
    id: 5,
    name: 'Ford E-350 Box Truck',
    status: 'active',
    driver: 'David Martinez',
    location: '321 Elm St - Warehouse District',
    eta: '30 min',
    mileage: 58200,
    maintenanceDue: false,
    vehicleType: 'box_truck',
    licensePlate: 'MNO-345',
    year: 2019,
    fuelLevel: 55,
    lastService: '2026-02-05',
    nextService: '2026-03-05'
  },
  {
    id: 6,
    name: 'Nissan NV2500',
    status: 'active',
    driver: 'Jennifer Lee',
    location: '654 Maple Blvd - Uptown',
    eta: '20 min',
    mileage: 34780,
    maintenanceDue: false,
    vehicleType: 'cargo_van',
    licensePlate: 'PQR-678',
    year: 2023,
    fuelLevel: 80,
    lastService: '2026-02-18',
    nextService: '2026-03-18'
  }
];

export const realWorldDeliveries: Delivery[] = [
  {
    id: 1,
    address: '123 Main St, Suite 100',
    customer: 'Downtown Bistro',
    status: 'in-transit',
    driver: 'Michael Rodriguez',
    items: 18,
    progress: 65,
    scheduledTime: '2026-02-24T10:00:00',
    estimatedArrival: '2026-02-24T10:15:00',
    notes: 'Deliver to back kitchen door',
    contactPerson: { name: 'Chef Marco', phone: '(555) 123-4567' },
    parkingInstructions: 'Use back alley parking lot',
    dropoffInstructions: 'Kitchen entrance, ring bell twice',
    accessCodes: ['#1234 for back door'],
    specialRequirements: ['No delivery after 4 PM']
  },
  {
    id: 2,
    address: '456 Oak Ave, 2nd Floor',
    customer: 'TechCorp Headquarters',
    status: 'pending',
    driver: 'Sarah Johnson',
    items: 12,
    progress: 0,
    scheduledTime: '2026-02-24T11:30:00',
    estimatedArrival: '2026-02-24T11:45:00',
    notes: 'Security clearance needed',
    contactPerson: { name: 'David Chen', phone: '(555) 987-6543' },
    parkingInstructions: 'Visitor parking, level P2',
    dropoffInstructions: 'Front desk, building lobby',
    accessCodes: ['Badge required for parking garage'],
    specialRequirements: ['Must sign in at front desk']
  },
  {
    id: 3,
    address: '789 Pine Rd',
    customer: 'Grand Hotel & Suites',
    status: 'delivered',
    driver: 'James Wilson',
    items: 24,
    progress: 100,
    scheduledTime: '2026-02-24T09:00:00',
    completedTime: '2026-02-24T09:25:00',
    notes: 'Large delivery for weekend events',
    contactPerson: { name: 'Maria Garcia', phone: '(555) 456-7890' },
    parkingInstructions: 'Use loading dock at rear',
    dropoffInstructions: 'Receiving department, basement level',
    accessCodes: ['Call extension 345 for receiving'],
    specialRequirements: ['Must check in with security']
  },
  {
    id: 4,
    address: '321 Elm St, Tech Park',
    customer: 'Morning Brew Cafe',
    status: 'in-transit',
    driver: 'Robert Chen',
    items: 15,
    progress: 30,
    scheduledTime: '2026-02-24T14:00:00',
    estimatedArrival: '2026-02-24T14:45:00',
    notes: 'Morning rush delivery',
    contactPerson: { name: 'Sarah Johnson', phone: '(555) 234-5678' },
    parkingInstructions: '15-minute loading zone',
    dropoffInstructions: 'Side entrance before 3pm',
    accessCodes: ['Ring bell for service entrance'],
    specialRequirements: ['Call 10 min before arrival']
  },
  {
    id: 5,
    address: '654 Maple Blvd',
    customer: 'Uptown Market',
    status: 'pending',
    driver: 'David Martinez',
    items: 32,
    progress: 0,
    scheduledTime: '2026-02-24T15:30:00',
    estimatedArrival: '2026-02-24T16:00:00',
    notes: 'Weekly stock delivery',
    contactPerson: { name: 'Tom Wilson', phone: '(555) 345-6789' },
    parkingInstructions: 'Loading dock behind building',
    dropoffInstructions: 'Stock room, follow yellow arrows',
    accessCodes: ['Gate code: 1987'],
    specialRequirements: ['Bring pallet jack']
  },
  {
    id: 6,
    address: '987 Cedar Ln',
    customer: 'City Hospital Cafeteria',
    status: 'in-transit',
    driver: 'Jennifer Lee',
    items: 28,
    progress: 50,
    scheduledTime: '2026-02-24T13:00:00',
    estimatedArrival: '2026-02-24T13:20:00',
    notes: 'Medical facility - strict protocols',
    contactPerson: { name: 'Dr. Patel', phone: '(555) 567-8901' },
    parkingInstructions: 'Designated delivery zone A',
    dropoffInstructions: 'Service entrance, door marked "Deliveries"',
    accessCodes: ['Security checkpoint pass required'],
    specialRequirements: ['Temperature-controlled items', 'Wear mask']
  }
];

export const realWorldClients: Client[] = [
  {
    id: 1,
    name: 'Downtown Bistro',
    businessName: 'Downtown Bistro & Bar',
    type: 'restaurant',
    address: '123 Main St, Cityville, ST 12345',
    contactPerson: { name: 'Chef Marco', phone: '(555) 123-4567', email: 'marco@downtownbistro.com' },
    phone: '(555) 123-4567',
    email: 'orders@downtownbistro.com',
    website: 'www.downtownbistro.com',
    preferredDeliveryTimes: ['10:00-11:00 AM', '2:00-3:00 PM'],
    parkingInstructions: 'Use back alley parking lot',
    dropoffInstructions: 'Deliver to back kitchen door',
    accessCodes: ['#1234 for back door'],
    specialRequirements: ['No delivery after 4 PM', 'Call upon arrival'],
    businessHours: 'Mon-Sun 11am-10pm',
    securityNotes: 'Back door requires code after 6pm',
    notes: 'Excellent customer, always tips drivers',
    lastDeliveryDate: '2026-02-24',
    deliveryFrequency: 'daily',
    rating: 5,
    primaryLocation: { lat: 40.7128, lng: -74.0060, address: '123 Main St' },
    parkingLocation: { lat: 40.7127, lng: -74.0061, notes: 'Back alley parking' },
    dropoffLocation: { lat: 40.7128, lng: -74.0059, notes: 'Kitchen entrance' },
    locationPhotos: [],
    created: '2026-01-15',
    updated: '2026-02-24'
  },
  {
    id: 2,
    name: 'TechCorp Headquarters',
    businessName: 'TechCorp Inc.',
    type: 'office',
    address: '456 Oak Ave, Tech Park, ST 67890',
    contactPerson: { name: 'David Chen', phone: '(555) 987-6543', email: 'david@techcorp.com' },
    phone: '(555) 987-6543',
    email: 'facilities@techcorp.com',
    website: 'www.techcorp.com',
    preferredDeliveryTimes: ['9:00 AM-12:00 PM'],
    parkingInstructions: 'Visitor parking, level P2',
    dropoffInstructions: 'Front desk, building lobby',
    accessCodes: ['Badge required for parking garage'],
    specialRequirements: ['Security clearance needed', 'Must sign in at front desk'],
    businessHours: 'Mon-Fri 8am-6pm',
    securityNotes: 'All visitors must be pre-registered',
    notes: 'Large orders for company events',
    lastDeliveryDate: '2026-02-23',
    deliveryFrequency: 'weekly',
    rating: 4,
    primaryLocation: { lat: 40.7580, lng: -73.9855, address: '456 Oak Ave' },
    parkingLocation: { lat: 40.7579, lng: -73.9856, notes: 'Visitor parking P2' },
    dropoffLocation: { lat: 40.7580, lng: -73.9854, notes: 'Main lobby' },
    locationPhotos: [],
    created: '2026-01-20',
    updated: '2026-02-23'
  },
  {
    id: 3,
    name: 'Grand Hotel & Suites',
    businessName: 'Grand Hotel & Suites',
    type: 'hotel',
    address: '789 Pine Rd, Townsville, ST 54321',
    contactPerson: { name: 'Maria Garcia', phone: '(555) 456-7890', email: 'maria@grandhotel.com' },
    phone: '(555) 456-7890',
    email: 'receiving@grandhotel.com',
    website: 'www.grandhotel.com',
    preferredDeliveryTimes: ['8:00-10:00 AM', '3:00-5:00 PM'],
    parkingInstructions: 'Use loading dock at rear',
    dropoffInstructions: 'Deliver to receiving department, basement level',
    accessCodes: ['Call extension 345 for receiving'],
    specialRequirements: ['Must check in with security', 'Use service elevator'],
    businessHours: '24/7 receiving',
    securityNotes: 'Security desk must be notified before entry',
    notes: 'Large deliveries every Monday',
    lastDeliveryDate: '2026-02-24',
    deliveryFrequency: 'weekly',
    rating: 4,
    primaryLocation: { lat: 40.7580, lng: -73.9855, address: '789 Pine Rd' },
    parkingLocation: { lat: 40.7579, lng: -73.9856, notes: 'Loading dock area' },
    dropoffLocation: { lat: 40.7580, lng: -73.9854, notes: 'Basement receiving' },
    locationPhotos: [],
    created: '2026-01-25',
    updated: '2026-02-24'
  },
  {
    id: 4,
    name: 'Morning Brew Cafe',
    businessName: 'Morning Brew Coffee Roasters',
    type: 'cafe',
    address: '321 Elm St, Tech Park, ST 54321',
    contactPerson: { name: 'Sarah Johnson', phone: '(555) 234-5678', email: 'sarah@morningbrew.com' },
    phone: '(555) 234-5678',
    email: 'orders@morningbrew.com',
    website: 'www.morningbrew.com',
    preferredDeliveryTimes: ['6:00-8:00 AM', '1:00-3:00 PM'],
    parkingInstructions: '15-minute loading zone',
    dropoffInstructions: 'Side entrance before 3pm',
    accessCodes: ['Ring bell for service entrance'],
    specialRequirements: ['Call 10 min before arrival', 'Morning rush critical'],
    businessHours: 'Mon-Fri 6am-6pm, Sat-Sun 7am-5pm',
    securityNotes: 'Alarm system active after hours',
    notes: 'Very time-sensitive deliveries',
    lastDeliveryDate: '2026-02-24',
    deliveryFrequency: 'daily',
    rating: 5,
    primaryLocation: { lat: 40.7580, lng: -73.9855, address: '321 Elm St' },
    parkingLocation: { lat: 40.7579, lng: -73.9856, notes: 'Loading zone' },
    dropoffLocation: { lat: 40.7580, lng: -73.9854, notes: 'Side entrance' },
    locationPhotos: [],
    created: '2026-02-01',
    updated: '2026-02-24'
  },
  {
    id: 5,
    name: 'Uptown Market',
    businessName: 'Uptown Grocery Market',
    type: 'retail',
    address: '654 Maple Blvd, Uptown District, ST 98765',
    contactPerson: { name: 'Tom Wilson', phone: '(555) 345-6789', email: 'tom@uptownmarket.com' },
    phone: '(555) 345-6789',
    email: 'receiving@uptownmarket.com',
    website: 'www.uptownmarket.com',
    preferredDeliveryTimes: ['7:00-10:00 AM', '2:00-4:00 PM'],
    parkingInstructions: 'Loading dock behind building',
    dropoffInstructions: 'Stock room, follow yellow arrows',
    accessCodes: ['Gate code: 1987'],
    specialRequirements: ['Bring pallet jack', 'Check in with receiving manager'],
    businessHours: 'Mon-Sat 8am-10pm, Sun 9am-8pm',
    securityNotes: '24/7 security patrol',
    notes: 'Weekly stock delivery, large orders',
    lastDeliveryDate: '2026-02-23',
    deliveryFrequency: 'weekly',
    rating: 4,
    primaryLocation: { lat: 40.7580, lng: -73.9855, address: '654 Maple Blvd' },
    parkingLocation: { lat: 40.7579, lng: -73.9856, notes: 'Loading dock' },
    dropoffLocation: { lat: 40.7580, lng: -73.9854, notes: 'Stock room entrance' },
    locationPhotos: [],
    created: '2026-02-05',
    updated: '2026-02-23'
  },
  {
    id: 6,
    name: 'City Hospital Cafeteria',
    businessName: 'City General Hospital',
    type: 'institution',
    address: '987 Cedar Ln, Medical District, ST 13579',
    contactPerson: { name: 'Dr. Patel', phone: '(555) 567-8901', email: 'patel@cityhospital.com' },
    phone: '(555) 567-8901',
    email: 'foodservices@cityhospital.com',
    website: 'www.cityhospital.com',
    preferredDeliveryTimes: ['6:00-9:00 AM', '12:00-2:00 PM'],
    parkingInstructions: 'Designated delivery zone A',
    dropoffInstructions: 'Service entrance, door marked "Deliveries"',
    accessCodes: ['Security checkpoint pass required'],
    specialRequirements: ['Temperature-controlled items', 'Wear mask', 'Health screening'],
    businessHours: '24/7 with restrictions',
    securityNotes: 'High security, ID check required',
    notes: 'Medical facility with strict protocols',
    lastDeliveryDate: '2026-02-24',
    deliveryFrequency: 'daily',
    rating: 5,
    primaryLocation: { lat: 40.7580, lng: -73.9855, address: '987 Cedar Ln' },
    parkingLocation: { lat: 40.7579, lng: -73.9856, notes: 'Delivery zone A' },
    dropoffLocation: { lat: 40.7580, lng: -73.9854, notes: 'Service entrance' },
    locationPhotos: [],
    created: '2026-02-10',
    updated: '2026-02-24'
  }
];

export const realWorldMaintenanceTasks: MaintenanceTask[] = [
  {
    id: 1,
    vehicle: 'Mercedes Sprinter 3500',
    type: 'Oil Change',
    dueDate: '2026-02-25',
    priority: 'high',
    estimatedDuration: '2 hours',
    partsNeeded: ['Oil filter', '5W-30 synthetic oil'],
    serviceProvider: 'City Auto Repair',
    costEstimate: 150
  },
  {
    id: 2,
    vehicle: 'Chevrolet Express 2500',
    type: 'Brake Inspection',
    dueDate: '2026-02-28',
    priority: 'medium',
    estimatedDuration: '1.5 hours',
    partsNeeded: ['Brake pads', 'Rotors'],
    serviceProvider: 'Fleet Maintenance Center',
    costEstimate: 300
  },
  {
    id: 3,
    vehicle: 'Ford Transit 250',
    type: 'Tire Rotation',
    dueDate: '2026-03-05',
    priority: 'low',
    estimatedDuration: '1 hour',
    partsNeeded: [],
    serviceProvider: 'Quick Tire Shop',
    costEstimate: 50
  },
  {
    id: 4,
    vehicle: 'Ram ProMaster 1500',
    type: 'Transmission Service',
    dueDate: '2026-03-01',
    priority: 'high',
    estimatedDuration: '3 hours',
    partsNeeded: ['Transmission fluid', 'Filter'],
    serviceProvider: 'Specialized Transmission',
    costEstimate: 450
  },
  {
    id: 5,
    vehicle: 'Ford E-350 Box Truck',
    type: 'Annual Inspection',
    dueDate: '2026-02-27',
    priority: 'medium',
    estimatedDuration: '4 hours',
    partsNeeded: ['Safety stickers', 'Lights'],
    serviceProvider: 'DMV Certified Inspector',
    costEstimate: 200
  }
];

export const realWorldSOPCategories: SOPCategory[] = [
  { id: 1, name: 'Delivery Procedures', count: 15, description: 'Standard delivery protocols and customer interaction guidelines' },
  { id: 2, name: 'Vehicle Maintenance', count: 12, description: 'Preventive maintenance and emergency repair procedures' },
  { id: 3, name: 'Safety Protocols', count: 8, description: 'Safety guidelines and emergency response procedures' },
  { id: 4, name: 'Customer Service', count: 10, description: 'Customer interaction and issue resolution guidelines' },
  { id: 5, name: 'Route Planning', count: 6, description: 'Efficient route planning and traffic management' },
  { id: 6, name: 'Food Safety', count: 7, description: 'Temperature control and food handling procedures' }
];