const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true}),errors=[],contexts=[];
 async function page(){const context=await browser.newContext({viewport:{width:1280,height:900}});contexts.push(context);const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));return p;}
 const owner=await page(),base='http://127.0.0.1:19391',pass='BrowserQaOnly-123456789';
 async function fill(p,values){for(const [name,value]of Object.entries(values))await p.getByLabel(name,{exact:true}).fill(value);}
 async function section(p,name){await p.getByRole('navigation').getByRole('button',{name,exact:true}).click();await p.getByRole('heading',{name,exact:true,level:1}).waitFor();}
 async function click(p,name){await p.getByRole('button',{name,exact:true}).last().click();}
 async function heading(p,name){await p.getByRole('heading',{name,exact:true}).waitFor();}
 try{
  const health=await (await fetch(base+'/api/health/ready')).json();assert.equal(health.revision,process.env.BROWSER_QA_REVISION||'a'.repeat(40),'Browser QA requires its dedicated disposable runtime');await owner.goto(base);await click(owner,'Initial setup');await fill(owner,{'Email':'browser-owner@example.invalid','Password':pass,'Your name':'Browser Owner','Workspace name':'Browser Fleet','Setup token':'browser-qa-disposable-only-token-20261001'});await click(owner,'Initial setup');await heading(owner,'Deliveries');
  await section(owner,'Vehicles');await fill(owner,{'Registration':'UI-001','Vehicle name':'QA Van'});await click(owner,'Add vehicle');await heading(owner,'QA Van');
  await section(owner,'Clients');await fill(owner,{'Client name':'Client <img src=x onerror="window.qaXss=true">','Contact email':'client@example.invalid'});await click(owner,'Add client');await heading(owner,'Client <img src=x onerror="window.qaXss=true">');assert.equal(await owner.evaluate(()=>window.qaXss),undefined);
  async function invitation(address,role){await section(owner,'Team');await owner.getByLabel('Invite email',{exact:true}).fill(address);await owner.getByLabel('Invite role',{exact:true}).selectOption(role);await click(owner,'Create invitation');const link=await owner.getByLabel('Invitation link',{exact:true}).inputValue();assert.match(link,/#invite=[a-f0-9]{64}$/);return link;}
  async function accept(address,name,link){const p=await page();await p.goto(link);await heading(p,'Accept invitation');assert.equal(new URL(p.url()).hash,'');await fill(p,{'Email':address,'Password':pass,'Your name':name});await click(p,'Accept invitation');await p.getByRole('navigation').waitFor();return p;}
  const driver=await accept('browser-driver@example.invalid','Browser Driver',await invitation('browser-driver@example.invalid','driver'));
  assert.equal(await driver.getByRole('navigation').getByRole('button').count(),2);assert.equal(await driver.getByRole('button',{name:'Team',exact:true}).count(),0);
  await section(owner,'Deliveries');await fill(owner,{'Reference':'UI-DELIVERY','Pickup address':'100 QA Street','Dropoff address':'200 QA Road'});await owner.getByLabel('Client',{exact:true}).selectOption({label:'Client <img src=x onerror="window.qaXss=true">'});await click(owner,'Create delivery');await heading(owner,'UI-DELIVERY');
  const delivery=owner.getByRole('article').filter({has:owner.getByRole('heading',{name:'UI-DELIVERY',exact:true})});await delivery.getByLabel('Driver',{exact:true}).selectOption({label:'Browser Driver'});await delivery.getByLabel('Vehicle',{exact:true}).selectOption({label:'QA Van'});await delivery.getByRole('button',{name:'Assign',exact:true}).click();await delivery.getByText('Status: assigned',{exact:true}).waitFor();
  await driver.reload();await heading(driver,'UI-DELIVERY');await click(driver,'Start delivery');await driver.getByText('Status: in_transit',{exact:true}).waitFor();await click(driver,'Complete delivery');await driver.getByText('Status: delivered',{exact:true}).waitFor();assert.equal(await driver.getByRole('button',{name:'Create delivery',exact:true}).count(),0);
  await section(owner,'Maintenance');await owner.getByLabel('Vehicle',{exact:true}).selectOption({label:'QA Van'});await owner.getByLabel('Service type',{exact:true}).selectOption('service');await fill(owner,{'Service title':'UI Service','Due date':'2026-10-01'});await click(owner,'Plan maintenance');await heading(owner,'UI Service');await click(owner,'Start maintenance');await owner.getByLabel('Service cost',{exact:true}).fill('123.45');await fill(owner,{'Currency code':'CAD','Service notes':'Completed in browser QA'});await click(owner,'Complete maintenance');await owner.getByText('Status: completed',{exact:true}).waitFor();
  await section(owner,'Reports');await owner.getByText('CAD 123.45',{exact:true}).waitFor();await owner.screenshot({path:'fleetvera-browser-report.png',fullPage:true});
  const mechanic=await accept('browser-mechanic@example.invalid','Browser Mechanic',await invitation('browser-mechanic@example.invalid','mechanic'));
  for(const label of ['Clients','Reports','Team','Deliveries'])assert.equal(await mechanic.getByRole('navigation').getByRole('button',{name:label,exact:true}).count(),0);
  await section(mechanic,'Maintenance');await mechanic.getByLabel('Vehicle',{exact:true}).selectOption({label:'QA Van'});await fill(mechanic,{'Service title':'Mechanic service','Due date':'2026-10-02'});await click(mechanic,'Plan maintenance');await heading(mechanic,'Mechanic service');const service=mechanic.getByRole('article').filter({has:mechanic.getByRole('heading',{name:'Mechanic service',exact:true})});await service.getByRole('button',{name:'Start maintenance',exact:true}).click();await service.getByText('Status: in_progress',{exact:true}).waitFor();await service.getByRole('button',{name:'Cancel maintenance',exact:true}).click();await service.getByText('Status: cancelled',{exact:true}).waitFor();
  await section(owner,'Team');const member=owner.getByRole('article').filter({has:owner.getByRole('heading',{name:'Browser Driver',exact:true})});await member.getByLabel('Workspace access',{exact:true}).selectOption('revoked');await member.getByRole('button',{name:'Save access',exact:true}).click();await member.getByText('Access revoked',{exact:true}).waitFor();await driver.reload();await heading(driver,'No workspace access');assert.equal(await driver.getByText('UI-DELIVERY',{exact:true}).count(),0);
  await owner.setViewportSize({width:390,height:844});await section(owner,'Deliveries');await heading(owner,'UI-DELIVERY');assert.ok(await owner.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await owner.screenshot({path:'fleetvera-browser-mobile.png',fullPage:true});
  await click(owner,'Sign out');await heading(owner,'Welcome to Fleetvera');assert.equal(await owner.getByText('UI-DELIVERY',{exact:true}).count(),0);
  assert.deepEqual(errors,[]);const result={status:'passed',browser:'Chromium',fresh_owner_bootstrap:true,invitation_acceptance:true,complete_delivery_lifecycle:true,complete_maintenance_lifecycle:true,mechanic_cancellation:true,owner_reporting:true,revoked_driver_visibility_denied:true,roles_hide_unavailable_actions:true,untrusted_names_render_as_text:true,mobile_no_horizontal_overflow:true,logout_clears_data:true,page_errors:errors,local_qa_secure_cookie_exception:true,production_mutated:false};fs.writeFileSync('fleetvera-browser-verification.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }catch(error){await owner.screenshot({path:'fleetvera-browser-failure.png',fullPage:true}).catch(()=>{});console.error(error);process.exitCode=1;}finally{for(const c of contexts)await c.close();await browser.close();}
})();
