import {expect,test} from '@playwright/test'
import {PrismaClient} from '@prisma/client'
import {SignJWT} from 'jose'
const db=new PrismaClient()
const ids={owner:'qa-owner',a:'qa-driver-a111111',b:'qa-driver-b222222',viewer:'qa-viewer',dispatch:'qa-dispatch',team:'qa-team'}
async function token(id:string,role:string){return new SignJWT({sub:id,email:`${id}@test.invalid`,name:'QA',role,purpose:'session'}).setProtectedHeader({alg:'HS256'}).setIssuedAt().setExpirationTime('1h').sign(new TextEncoder().encode(process.env.JWT_SECRET!))}
async function auth(page:import('@playwright/test').Page,id:string,role:string){const origin=new URL(test.info().project.use.baseURL as string);await page.context().clearCookies();await page.context().addCookies([{name:'token',value:await token(id,role),domain:origin.hostname,path:'/',httpOnly:true,sameSite:'Lax'},{name:'fleetflow_team',value:ids.team,domain:origin.hostname,path:'/',sameSite:'Lax'}])}
test.beforeAll(async()=>{
 await db.user.createMany({data:[{id:ids.owner,email:'qa-owner@test.invalid',name:'Owner',role:'fleet_manager',onboardingCompleted:true},{id:ids.a,email:'qa-a@test.invalid',name:'Alex Driver',role:'driver',onboardingCompleted:true},{id:ids.b,email:'qa-b@test.invalid',name:'Alex Driver',role:'driver',onboardingCompleted:true},{id:ids.viewer,email:'qa-viewer@test.invalid',name:'Viewer',role:'viewer',onboardingCompleted:true},{id:ids.dispatch,email:'qa-dispatch@test.invalid',name:'Dispatch',role:'dispatcher',onboardingCompleted:true}],skipDuplicates:true});await db.team.upsert({where:{id:ids.team},update:{},create:{id:ids.team,name:'QA Team',ownerId:ids.owner}})
 for(const [id,userId,role] of [['m-a',ids.a,'DRIVER'],['m-b',ids.b,'DRIVER'],['m-view',ids.viewer,'VIEWER'],['m-dispatch',ids.dispatch,'DISPATCHER']] as const)await db.teamMember.upsert({where:{id},update:{role,status:'ACCEPTED'},create:{id,teamId:ids.team,userId,role,status:'ACCEPTED'}})
})
test.afterAll(async()=>{await db.delivery.deleteMany({where:{teamId:ids.team}});await db.vehicle.deleteMany({where:{teamId:ids.team}});await db.team.deleteMany({where:{id:ids.team}});await db.user.deleteMany({where:{id:{in:Object.values(ids).filter(id=>id!==ids.team)}}});await db.$disconnect()})
test('real forms, driver API boundaries, reassignment and demotion use stable ids',async({page})=>{
 const requestOrigin=new URL(test.info().project.use.baseURL as string).origin
 await auth(page,ids.owner,'fleet_manager');await page.goto('/vehicles');await page.getByRole('button',{name:/add vehicle/i}).first().click();await page.getByLabel('e.g., Delivery Van 1').fill('QA Van');const options=page.getByLabel('Assigned Driver').getByRole('option',{name:/Alex Driver/});await expect(options).toHaveCount(2);await expect(options.nth(0)).not.toHaveText(/@/);await page.getByLabel('Assigned Driver').selectOption(ids.a);await page.getByLabel('Add New Vehicle').getByRole('button',{name:'Add Vehicle'}).click();const vehicle=await expect.poll(()=>db.vehicle.findFirst({where:{teamId:ids.team,name:'QA Van'}}).then(v=>v?.assignedDriverId)).toBe(ids.a).then(()=>db.vehicle.findFirstOrThrow({where:{teamId:ids.team,name:'QA Van'}}))
 await page.goto('/deliveries');await page.getByRole('button',{name:/new delivery/i}).click();await page.getByLabel('e.g., Acme Corporation').fill('QA Customer');await page.getByLabel('Full street address').fill('1 QA Road');await page.getByLabel('Assigned Driver').selectOption(ids.a);await page.getByLabel('Add New Delivery').getByRole('button',{name:'Add Delivery'}).click();const delivery=await expect.poll(()=>db.delivery.findFirst({where:{teamId:ids.team,customer:'QA Customer'}})).not.toBeNull().then(()=>db.delivery.findFirstOrThrow({where:{teamId:ids.team,customer:'QA Customer'}}))
 const other=await db.delivery.create({data:{customer:'Other Driver',address:'2 QA Road',ownerId:ids.owner,teamId:ids.team,assignedDriverId:ids.b,driver:'Alex Driver',contactPerson:'secret',accessCodes:'secret',securityNotes:'secret',photos:'secret',notes:'secret'}})
 await auth(page,ids.a,'driver');let response=await page.request.get('/api/deliveries');let body=await response.json();expect(body.data.map((x:{id:string})=>x.id)).toEqual([delivery.id]);for(const key of ['contactPerson','accessCodes','securityNotes','photos','notes','ownerId','teamId'])expect(body.data[0]).not.toHaveProperty(key)
 expect((await page.request.get(`/api/deliveries/${other.id}`)).status(),'unassigned delivery detail must not disclose existence').toBe(404)
 expect((await page.request.get(`/api/deliveries/${other.id}/events`)).status(),'unassigned delivery events must not disclose existence').toBe(404)
 expect((await page.request.patch(`/api/deliveries/${other.id}/status`,{headers:{origin:requestOrigin},data:{status:'in-transit'}})).status(),'unassigned delivery mutation must not disclose existence').toBe(404)
 expect((await page.request.get(`/api/vehicles/${vehicle.id}`)).status()).toBe(200)
 await auth(page,ids.owner,'fleet_manager');expect((await page.request.put(`/api/deliveries/${delivery.id}`,{data:{assignedDriverId:ids.b}})).ok()).toBe(true);await auth(page,ids.a,'driver');body=await (await page.request.get('/api/deliveries')).json();expect(body.data).toHaveLength(0);await auth(page,ids.b,'driver');body=await (await page.request.get('/api/deliveries')).json();expect(body.data.map((x:{id:string})=>x.id)).toEqual(expect.arrayContaining([delivery.id,other.id]))
 await db.vehicle.update({where:{id:vehicle.id},data:{assignedDriverId:ids.a,driver:'Alex Driver'}});await db.delivery.update({where:{id:delivery.id},data:{assignedDriverId:ids.a,driver:'Alex Driver'}});await auth(page,ids.owner,'fleet_manager');response=await page.request.put('/api/team',{headers:{origin:requestOrigin},data:{memberId:'m-a',role:'VIEWER'}});expect(response.ok()).toBe(true);expect((await db.vehicle.findUniqueOrThrow({where:{id:vehicle.id}})).assignedDriverId).toBeNull();expect((await db.delivery.findUniqueOrThrow({where:{id:delivery.id}})).assignedDriverId).toBeNull();expect(await db.auditLog.count({where:{teamId:ids.team,entityType:'driver_assignment',entityId:ids.a}})).toBeGreaterThan(0)
 await auth(page,ids.dispatch,'dispatcher');body=await (await page.request.get('/api/deliveries')).json();expect(body.data.map((x:{id:string})=>x.id)).toContain(delivery.id);await auth(page,ids.viewer,'viewer');expect((await page.request.get('/api/drivers')).status()).toBe(403)
})
