require('ts-node').register({transpileOnly:true,compilerOptions:{module:'CommonJS',moduleResolution:'Node'}})
const path=require('path'),Module=require('module'),resolve=Module._resolveFilename;Module._resolveFilename=function(request,parent,isMain,options){return resolve.call(this,request.startsWith('@/')?path.join(__dirname,'..',request.slice(2)):request,parent,isMain,options)}
const fixtures=require('../lib/ai/evaluation-fixtures.json'),pricing=require('../lib/ai/pricing.json'),recordings=require('../lib/ai/provider-evaluation-records.json');const {evaluationFixtureSchema,runEvaluationHarness,evaluateAiCases,releaseGate,validatePricingAlignment,aiConfigFingerprint,validateProviderEvaluationRecord}=require('../lib/ai/evaluation')
async function main(){
 if(!validatePricingAlignment(process.env,pricing))throw new Error('Configured AI provider/model has no exact versioned pricing entry')
 const parsed=evaluationFixtureSchema.parse(fixtures),provider=process.env.AI_PROVIDER?.trim()||'disabled',model=provider==='disabled'?'none@v1':process.env.OPENAI_MODEL?.trim(),configVersion=process.env.AI_CONFIG_VERSION?.trim()||'1',fingerprint=aiConfigFingerprint(provider,model,configVersion),evaluationVersion='task9-realpath@v2';let evaluationMode='deterministic-pipeline',capturedAt=new Date().toISOString(),options={now:new Date('2026-08-08T12:00:00Z')}
 if(provider!=='disabled'){const candidate=recordings.find(item=>item&&item.provider===provider&&item.modelVersion===model&&item.configFingerprint===fingerprint&&item.evaluationVersion===evaluationVersion);if(!candidate)throw new Error('Enabled AI requires an exact recorded provider-quality evaluation');const record=validateProviderEvaluationRecord(candidate,parsed,{provider,modelVersion:model,configFingerprint:fingerprint,evaluationVersion});const age=Date.now()-Date.parse(record.capturedAt);if(!Number.isFinite(age)||age<0||age>30*86400000)throw new Error('Recorded provider-quality evaluation is stale');const outputs=new Map(record.outputs.filter(item=>'result'in item).map(item=>[item.fixtureId,item.result]));options={...options,latencySource:'recorded',attribution:{provider,modelVersion:model},generate:async(_payload,requestOptions)=>{const id=String(requestOptions.dependencies?.requestId?.()||'').replace(/^eval-/,'');const result=outputs.get(id);if(!result)throw new Error('Recorded output missing');return result}};evaluationMode='provider-quality-recorded';capturedAt=record.capturedAt}
 const outcomes=await runEvaluationHarness(parsed,options),score=evaluateAiCases(parsed,outcomes,pricing,{provider,modelVersion:model}),gate=releaseGate(score,{requireGeneratedSupported:provider!=='disabled'})
 const persist=Boolean(process.env.DATABASE_URL)&&process.env.AI_EVAL_STDOUT_ONLY!=='true';let mode='offline-stdout'
 if(persist){const{PrismaClient}=require('@prisma/client');const db=new PrismaClient();try{await db.aiEvaluationRun.create({data:{evaluationVersion,mode:evaluationMode,configFingerprint:fingerprint,capturedAt:new Date(capturedAt),provider,modelVersion:model,citationAccuracyBps:Math.round(score.citationAccuracy*10000),crossTenantFailures:score.crossTenantFailures,passed:gate.passed,score:JSON.stringify(score)}});mode='persisted'}finally{await db.$disconnect()}}
 process.stdout.write(`${JSON.stringify({mode,evaluationMode,evaluationVersion,capturedAt,provider,modelVersion:model,configFingerprint:fingerprint,pricing:{currency:pricing.currency,asOf:pricing.asOf,source:pricing.source},score,gate},null,2)}\n`);if(!gate.passed)process.exitCode=1
}
main().catch(error=>{console.error(error instanceof Error?error.message:'AI evaluation failed');process.exitCode=1})
